version: "3.3"

services:
    app:
        container_name: lymantria
        image: easilok/lymantria
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "9090:9090" 
